### ISSUE TITLE
tls检测问题

### ISSUE THREAD

**Issue by akaagiao1** [TinrLin/ShadowTLS-v3-build-tutorial#1]
![image](https://github.com/TinrLin/ShadowTLS-v3-build-tutorial/assets/94331537/9b5efce9-1841-41f6-950d-ded2baa31f88)
大佬上面的域名是shadowtls作者推荐的为啥咱的脚本显示tls检测失败啊

**Comment by TinrLin** [comment]
已修复，刚开始设置的超时时间比较短，有些vps验证的时候特别慢，所以没有验证完成
